# Events
on:
  # Push to master
  push:
    branches: 
      - 'master'
  # Manual trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Set up cache
        uses: Swatinem/rust-cache@v2

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings          
      - name: Install cargo check tools
        run: |
          cargo install --locked cargo-deny || true
          cargo install --locked cargo-outdated || true
          cargo install --locked cargo-audit || true
      - name: Check
        run: |
          cargo deny check
          cargo outdated --exit-code 1
          rm -rf ~/.cargo/advisory-db
          cargo audit
      - name: Test
        run: cargo test
